# MATH 6243 Project Data Cleaning
# Mishka, Sandy, and Celia

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# reading in the data
df = pd.read_csv("police_use_of_force.csv")
print(df.shape)
df.head(10)

(41416, 30)

,X,Y,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,Is911Call,PrimaryOffense,SubjectInjury,ForceReportNumber,...,TotalCityCallsForYear,TotalPrecinctCallsForYear,TotalNeighborhoodCallsForYear,CenterGBSID,CenterLatitude,CenterLongitude,CenterX,CenterY,DateAdded,OBJECTID
0,-93.298111,45.015878,67321960,08-001245,2008/01/02 02:20:27+00,Fight,Yes,DISCON,NaN,1,...,322402,80434.0,7483,18760,45.015878,-93.298111,-1.038590e+07,5.624022e+06,2024/08/20 08:21:05+00,1
1,-93.225106,44.898115,67321961,08-003786,2008/01/04 13:30:33+00,Suspicious Vehicle,Yes,FLEE,Yes,2,...,322402,84018.0,1927,20947,44.898115,-93.225106,-1.037777e+07,5.605496e+06,2024/08/20 08:21:05+00,2
2,-93.269582,44.962688,67321962,08-006776,2008/01/07 14:31:58+00,Trespass in Boarded Dwell,Yes,NARC,No,3,...,322402,84018.0,10316,18561,44.962688,-93.269582,-1.038272e+07,5.615649e+06,2024/08/20 08:21:05+00,3
3,-93.204183,44.906431,67321963,08-013439,2008/01/13 23:29:57+00,Emotionally Disturb Person,Yes,FENTRY,Yes,1,...,322402,84018.0,1101,16263,44.906432,-93.204183,-1.037544e+07,5.606803e+06,2024/08/20 08:21:05+00,4
4,-93.306312,44.979777,67321964,08-016088,2008/01/16 20:03:10+00,Person with a Gun,Yes,OBSTRU,No,1,...,322402,80434.0,2514,25431,44.979777,-93.306312,-1.038681e+07,5.618338e+06,2024/08/20 08:21:05+00,5
5,-93.288659,44.959124,67321965,08-016285,2008/01/16 23:47:30+00,Assault in Progress,Yes,POVIOL,No,1,...,322402,55689.0,5734,16533,44.959124,-93.288659,-1.038485e+07,5.615089e+06,2024/08/20 08:21:05+00,6
6,-93.293698,45.013131,67321966,08-021196,2008/01/22 15:56:16+00,Traffic Law Enforcement,No,OBSTRU,No,1,...,322402,80434.0,7483,10388,45.013131,-93.293698,-1.038541e+07,5.623589e+06,2024/08/20 08:21:05+00,7
7,-93.257320,45.011083,67321967,08-030673,2008/02/01 03:20:35+00,Domestic Abuse-In Progress,Yes,911INT,No,1,...,322402,48901.0,4939,11160,45.011083,-93.257320,-1.038136e+07,5.623266e+06,2024/08/20 08:21:05+00,8
8,-93.295639,45.000883,67321968,08-030704,2008/02/01 06:15:20+00,Attempt Pick-Up,No,CHLDAB,NaN,1,...,322402,80434.0,15344,22445,45.000883,-93.295639,-1.038562e+07,5.621661e+06,2024/08/20 08:21:05+00,9
9,-93.253396,44.988867,67321969,08-031711,2008/02/02 01:19:05+00,Poss Personal Injury Acc,Yes,DWI,Yes,1,...,322402,48901.0,4858,19846,44.988867,-93.253396,-1.038092e+07,5.619769e+06,2024/08/20 08:21:05+00,10

In [ ]:
# finding all the null values
# the important variables are ForceType, Sex, Race, TypeOfResistance, Neighborhood, Problem, PrimaryOffense
# maybe we also want TypeOfResistance? 
df.isnull().sum()

X                                    0
Y                                    0
PoliceUseOfForceID                   0
CaseNumber                           0
ResponseDate                        17
Problem                           1853
Is911Call                         1496
PrimaryOffense                    1487
SubjectInjury                    20516
ForceReportNumber                    0
SubjectRole                       5209
SubjectRoleNumber                 3730
ForceType                         1479
ForceTypeAction                      0
Race                              1479
Sex                               1479
EventAge                          6493
TypeOfResistance                 11455
Precinct                          1522
Neighborhood                       229
TotalCityCallsForYear                0
TotalPrecinctCallsForYear         1479
TotalNeighborhoodCallsForYear        0
CenterGBSID                          0
CenterLatitude                       0
CenterLongitude                      0
CenterX                              0
CenterY                              0
DateAdded                            0
OBJECTID                             0
dtype: int64

In [ ]:
# dropping rows with null values in important variables
important = ['ForceType', 'Sex', 'Race', 'TypeOfResistance', 'Neighborhood', 'Problem', 'PrimaryOffense']
df_cleaned = df.dropna(subset=important)
df_cleaned.shape

(29716, 30)

With dropping all of the rows with any nulls in the 'important' columns, we still have almost 30,000 rows of data.

In [ ]:
# now getting a df that only has the needed feature variables and target ('ForceType)
# all of these are categorical variables also
df_final = df_cleaned[important]
df_final

,ForceType,Sex,Race,TypeOfResistance,Neighborhood,Problem,PrimaryOffense
0,Bodily Force,Female,Black,Tensed,Folwell,Fight,DISCON
1,Bodily Force,Male,Black,Fled in Vehicle,Wenonah,Suspicious Vehicle,FLEE
2,Bodily Force,Male,Black,Verbal Non-Compliance,Ventura Village,Trespass in Boarded Dwell,NARC
3,Taser,Male,White,Tensed,Minnehaha,Emotionally Disturb Person,FENTRY
4,Bodily Force,Male,White,Verbal Non-Compliance,Harrison,Person with a Gun,OBSTRU
...,...,...,...,...,...,...,...
39218,Bodily Force,Female,Unknown,Tensed ...,Near - North,Emotionally Disturb Person,CIC
39220,Bodily Force,Female,Black,Assaulted Officer ...,Loring Park,Assist a Disabled Person,DISCON
39425,Bodily Force,Male,Unknown,X,Phillips West,Overdose w/All,CIC
39444,Bodily Force,Male,Black,X,Folwell,Attempt Pick-Up,PFARM
39649,Taser,Female,Black,X,Near - North,Suspicious Vehicle,STOLMV

In [14]:
# saving the cleaned data as a new csv
df_final.to_csv("cleaned_data.csv")