# MATH 6243 Project Data Cleaning
# Mishka, Sandy, and Celia

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [59]:
# reading in the data
df = pd.read_csv("police_use_of_force.csv")
print(df.shape)
df.head(10)

(41416, 30)

,X,Y,PoliceUseOfForceID,CaseNumber,ResponseDate,Problem,Is911Call,PrimaryOffense,SubjectInjury,ForceReportNumber,...,TotalCityCallsForYear,TotalPrecinctCallsForYear,TotalNeighborhoodCallsForYear,CenterGBSID,CenterLatitude,CenterLongitude,CenterX,CenterY,DateAdded,OBJECTID
0,-93.298111,45.015878,67321960,08-001245,2008/01/02 02:20:27+00,Fight,Yes,DISCON,NaN,1,...,322402,80434.0,7483,18760,45.015878,-93.298111,-1.038590e+07,5.624022e+06,2024/08/20 08:21:05+00,1
1,-93.225106,44.898115,67321961,08-003786,2008/01/04 13:30:33+00,Suspicious Vehicle,Yes,FLEE,Yes,2,...,322402,84018.0,1927,20947,44.898115,-93.225106,-1.037777e+07,5.605496e+06,2024/08/20 08:21:05+00,2
2,-93.269582,44.962688,67321962,08-006776,2008/01/07 14:31:58+00,Trespass in Boarded Dwell,Yes,NARC,No,3,...,322402,84018.0,10316,18561,44.962688,-93.269582,-1.038272e+07,5.615649e+06,2024/08/20 08:21:05+00,3
3,-93.204183,44.906431,67321963,08-013439,2008/01/13 23:29:57+00,Emotionally Disturb Person,Yes,FENTRY,Yes,1,...,322402,84018.0,1101,16263,44.906432,-93.204183,-1.037544e+07,5.606803e+06,2024/08/20 08:21:05+00,4
4,-93.306312,44.979777,67321964,08-016088,2008/01/16 20:03:10+00,Person with a Gun,Yes,OBSTRU,No,1,...,322402,80434.0,2514,25431,44.979777,-93.306312,-1.038681e+07,5.618338e+06,2024/08/20 08:21:05+00,5
5,-93.288659,44.959124,67321965,08-016285,2008/01/16 23:47:30+00,Assault in Progress,Yes,POVIOL,No,1,...,322402,55689.0,5734,16533,44.959124,-93.288659,-1.038485e+07,5.615089e+06,2024/08/20 08:21:05+00,6
6,-93.293698,45.013131,67321966,08-021196,2008/01/22 15:56:16+00,Traffic Law Enforcement,No,OBSTRU,No,1,...,322402,80434.0,7483,10388,45.013131,-93.293698,-1.038541e+07,5.623589e+06,2024/08/20 08:21:05+00,7
7,-93.257320,45.011083,67321967,08-030673,2008/02/01 03:20:35+00,Domestic Abuse-In Progress,Yes,911INT,No,1,...,322402,48901.0,4939,11160,45.011083,-93.257320,-1.038136e+07,5.623266e+06,2024/08/20 08:21:05+00,8
8,-93.295639,45.000883,67321968,08-030704,2008/02/01 06:15:20+00,Attempt Pick-Up,No,CHLDAB,NaN,1,...,322402,80434.0,15344,22445,45.000883,-93.295639,-1.038562e+07,5.621661e+06,2024/08/20 08:21:05+00,9
9,-93.253396,44.988867,67321969,08-031711,2008/02/02 01:19:05+00,Poss Personal Injury Acc,Yes,DWI,Yes,1,...,322402,48901.0,4858,19846,44.988867,-93.253396,-1.038092e+07,5.619769e+06,2024/08/20 08:21:05+00,10

In [60]:
# finding all the null values
# the important variables are ForceType, Sex, Race, TypeOfResistance, Neighborhood, Problem, PrimaryOffense
# maybe we also want TypeOfResistance? 
df[['ForceType', 'Race', 'Sex', 'Problem', 'TypeOfResistance', 'CenterLatitude', 'CenterLongitude']].isnull().sum()

ForceType            1479
Race                 1479
Sex                  1479
Problem              1853
TypeOfResistance    11455
CenterLatitude          0
CenterLongitude         0
dtype: int64

In [61]:
# dropping rows with null values in important variables
important = ['ForceType', 'Sex', 'Race', 'TypeOfResistance', 'Neighborhood', 'Problem', 'PrimaryOffense', 'CenterLatitude', 'CenterLongitude']
df_cleaned = df.dropna(subset=important)
df_dropped = df[df[important].isna().any(axis=1)]
df_cleaned.shape, df.shape

((29716, 30), (41416, 30))

With dropping all of the rows with any nulls in the 'important' columns, we still have almost 30,000 rows of data.

In [62]:
# now getting a df that only has the needed feature variables and target ('ForceType)
# all of these are categorical variables also
df_final = df_cleaned[important]
df_final

,ForceType,Sex,Race,TypeOfResistance,Neighborhood,Problem,PrimaryOffense,CenterLatitude,CenterLongitude
0,Bodily Force,Female,Black,Tensed,Folwell,Fight,DISCON,45.015878,-93.298111
1,Bodily Force,Male,Black,Fled in Vehicle,Wenonah,Suspicious Vehicle,FLEE,44.898115,-93.225106
2,Bodily Force,Male,Black,Verbal Non-Compliance,Ventura Village,Trespass in Boarded Dwell,NARC,44.962688,-93.269582
3,Taser,Male,White,Tensed,Minnehaha,Emotionally Disturb Person,FENTRY,44.906432,-93.204183
4,Bodily Force,Male,White,Verbal Non-Compliance,Harrison,Person with a Gun,OBSTRU,44.979777,-93.306312
...,...,...,...,...,...,...,...,...,...
39218,Bodily Force,Female,Unknown,Tensed ...,Near - North,Emotionally Disturb Person,CIC,44.996862,-93.291053
39220,Bodily Force,Female,Black,Assaulted Officer ...,Loring Park,Assist a Disabled Person,DISCON,44.971539,-93.276738
39425,Bodily Force,Male,Unknown,X,Phillips West,Overdose w/All,CIC,44.956428,-93.262590
39444,Bodily Force,Male,Black,X,Folwell,Attempt Pick-Up,PFARM,45.018610,-93.301278
39649,Taser,Female,Black,X,Near - North,Suspicious Vehicle,STOLMV,44.992282,-93.299442

In [63]:
print(df_dropped['Race'].value_counts(), df['Race'].value_counts())

Race
Black                 4024
not recorded          3834
White                 1628
Native American        409
Unknown                272
Asian                   45
Other / Mixed Race       5
Pacific Islander         4
Name: count, dtype: int64 Race
Black                 22421
White                  8845
not recorded           4217
Native American        1980
Other / Mixed Race     1095
Unknown                 913
Asian                   457
Pacific Islander          9
Name: count, dtype: int64

~39% of dropped race is Black, ~38% of dropped race is not recorded, ~16% dropped white, ~7% dropped other

~56% of original data is Black, ~10% not recorded, ~22% white, ~11% other

In [64]:
print(df_dropped['Sex'].value_counts(), df['Sex'].value_counts())

Sex
Male            5231
not recorded    3828
Female          1113
Unknown           49
Name: count, dtype: int64 Sex
Male            30662
Female           4943
not recorded     4094
Unknown           238
Name: count, dtype: int64

~51% of dropped rows are male, ~37% not recorded, ~11% female, ~0.5% unknown

~77% original data is male, ~12% female, ~10% not recorded, ~0.5% unknown

In [65]:
print(df_dropped['ForceType'].value_counts()), df['ForceType'].value_counts()

ForceType
Bodily Force                   7586
Taser                          1821
Chemical Irritant               542
Less Lethal                     131
Maximal Restraint Technique      58
Improvised Weapon                57
Police K9 Bite                   20
Gun Point Display                 3
Firearm                           2
Baton                             1
Name: count, dtype: int64

(None,
 ForceType
 Bodily Force                   28997
 Chemical Irritant               4667
 Taser                           4628
 Gun Point Display                439
 Improvised Weapon                405
 Police K9 Bite                   310
 Maximal Restraint Technique      195
 Less Lethal                      178
 Baton                             58
 Firearm                           44
 Less Lethal Projectile            16
 Name: count, dtype: int64)

In [66]:
# saving the cleaned data as a new csv
df_final.to_csv("cleaned_data.csv")

## Further Data Cleaning

We already dropped the values that had a null ForceType and null features, but now we need to clean up/group the categories we want to use for analysis to make everything more feasible.

In [67]:
# reading in the data and looking at our target variable
# it looks like we are going to want to group categories
df = pd.read_csv('cleaned_data.csv')
print(df['ForceType'].value_counts())
print(df.shape)

df['ForceType'] = df['ForceType'].replace('Less Lethal Projectile', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Baton', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Less Lethal', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Taser', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Improvised Weapon', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Police K9 Bite', 'Less Lethal Weapons')
df['ForceType'] = df['ForceType'].replace('Gun Point Display', 'Guns')
df['ForceType'] = df['ForceType'].replace('Firearm', 'Guns')
df['ForceType'] = df['ForceType'].replace('Maximal Restraint Technique', 'Bodily Force')

print(df['ForceType'].value_counts())

ForceType
Bodily Force                   21411
Chemical Irritant               4125
Taser                           2807
Gun Point Display                436
Improvised Weapon                348
Police K9 Bite                   290
Maximal Restraint Technique      137
Baton                             57
Less Lethal                       47
Firearm                           42
Less Lethal Projectile            16
Name: count, dtype: int64
(29716, 10)
ForceType
Bodily Force           21548
Chemical Irritant       4125
Less Lethal Weapons     3565
Guns                     478
Name: count, dtype: int64

less lethal projectile, baton, less lethal, taser, improvised weapon, police k9 bite  - 'less-lethal weapons'

gun point display and firearm together - 'guns'

add maximal restraint technique to bolidy force - 'bodily force'

chemical irritant by itself

In [68]:
# now looking at race - we also will want to group these
df['Race'] = df['Race'].replace('Other / Mixed Race', 'other')
df['Race'] = df['Race'].replace('Pacific Islander', 'other')
df['Race'] = df['Race'].replace('Asian', 'other')
df['Race'] = df['Race'].replace('Unknown', 'other')
df = df[df['Race'] != 'not recorded']
print(df['Race'].value_counts())

Race
Black              18397
White               7217
other               2148
Native American     1571
Name: count, dtype: int64

Group other/mixed race, asian, unknown,  pacific islander together and drop 'not recorded'

In [69]:
df = df[df['Sex'] != 'not recorded']
print(df['Sex'].value_counts())

Sex
Male       25340
Female      3800
Unknown      189
Name: count, dtype: int64

In [70]:
# TypeOfResistance was giving me problems, so I am looking at
# all of the unique values
df['TypeOfResistance'].unique()

array(['Tensed', 'Fled in Vehicle', 'Verbal Non-Compliance',
       'Unspecified', 'Commission of Crime', 'Fled on Foot',
       'Assaulted Officer', 'Assaulting Police Horse',
       'Assaulting Police K9', 'TENSED', 'tensed',
       'Other                                                                          ',
       'commission of crime', 'verbal non-compliance',
       'COMMISSION OF CRIME',
       'Tensed                                                                         ',
       'Fled on Foot                                                                   ',
       'Commission of a Crime                                                          ',
       'Assaulted Officer                                                              ',
       'Verbal Non-Compliance                                                          ',
       'Fled in a Vehicle                                                              ',
       'Assaulted Police Horse                                                         ',
       'X',
       'Assaulted Police K9                                                            '],
      dtype=object)

This data ^ is super messy and will need to be cleaned before building models.

In [71]:
# stripping the responses down since they are not clean enough to see 
# first removing capitalization and spaces 
df['TypeOfResistance'] = df['TypeOfResistance'].str.strip().str.lower()

# mapping phrasing together 
df['TypeOfResistance'] = df['TypeOfResistance'].replace({
    'commission of a crime': 'commission of crime',
    'fled in a vehicle': 'fled in vehicle',
    'assaulted police horse': 'assaulting police horse',
    'assaulted police k9': 'assaulting police k9'
})

# final cleaner results
print(df['TypeOfResistance'].value_counts())

TypeOfResistance
tensed                     8088
commission of crime        6146
fled on foot               4542
assaulted officer          3260
verbal non-compliance      3218
unspecified                2082
other                      1056
fled in vehicle             838
assaulting police horse      51
x                            33
assaulting police k9         15
Name: count, dtype: int64

In [72]:
df = df[df['TypeOfResistance'] != 'x']
df['TypeOfResistance'] = df['TypeOfResistance'].replace('assaulting police horse', 'assaulting police officer or animal')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('assaulting police k9', 'assaulting police officer or animal')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('assaulted officer', 'assaulting police officer or animal')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('unspecified', 'other/unspecified')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('other', 'other/unspecified')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('fled on foot', 'fled')
df['TypeOfResistance'] = df['TypeOfResistance'].replace('fled in vehicle', 'fled')
df['TypeOfResistance'].value_counts()

TypeOfResistance
tensed                                 8088
commission of crime                    6146
fled                                   5380
assaulting police officer or animal    3326
verbal non-compliance                  3218
other/unspecified                      3138
Name: count, dtype: int64

drop the rows that have x; group assaulted officer, assaulted horse, and assaulted dog together

In [73]:
# I don't think this is going to be helpful for analysis since it 
# is so granular
len(df['Neighborhood'].unique())

86

In [74]:
# there are 132 unique 'problems', which will also need to be grouped
# into categories
print(len(df['Problem'].unique()))
print((df['Problem'].unique()))

131
['Fight ' 'Suspicious Vehicle ' 'Trespass in Boarded Dwell '
 'Emotionally Disturb Person ' 'Person with a Gun ' 'Assault in Progress '
 'Traffic Law Enforcement ' 'Domestic Abuse-In Progress '
 'Attempt Pick-Up ' 'Poss Personal Injury Acc '
 'Burglary Biz - In Progress ' 'Suspicious Person '
 'Person with a Weapon ' 'Check the Welfare ' 'Disturbance '
 'Recover Vehicle ' 'Audible Residential Alarm '
 'High Risk Warrant Entry ' 'Motor Vehicle Chase ' 'Miscellaneous '
 'Theft ' 'Suspected Hazard ' 'Domestic with Weapons ' 'Neighbor Trouble '
 'Unknown Trouble ' 'On Site ' 'Music-Loud ' 'Drunk/Intoxicated Person '
 'Damage Property-In Progress' 'Unwanted Person ' 'Chase on Foot '
 'Crim Sex Conduct/Report ' 'Paramedic Needs Help ' 'Assist an Officer '
 'Assist EMS Personnel ' 'Burglary Dwlng In Progress ' 'Code 3 '
 'Robbery of Person ' 'Loud Party ' 'Narcotics '
 'Domestic Abuse Report Only ' 'Officer Needs Help ' 'Domestic '
 'Customer Trouble ' 'Assault Report Only ' 'Property Damage Accident '
 'Stabbing ' 'Prowler ' 'Robbery Dwell in Progress ' 'Attempted Suicide '
 'Unknown Wireless/Cell Phone' 'Down Outside-One ' 'Sound of Shots Fired '
 'ShotSpotter Activation ' 'Slumper ' 'Retrieve Prop/Dom Situation'
 'Walk Through a Building ' 'Auto Theft in Progress ' 'Threats '
 'Aircraft Crash in City ' 'Assist Other Agency '
 'Audible Business Alarm ' 'Theft - Report Only ' 'Shooting '
 'Silent Alarm ' 'Bait Vehicle Auto Theft ' 'Transportation '
 'Personal Injury Accident ' 'Property Damage/Hit & Run '
 'Personal Inj/Hit and Run ' 'Robbery of Biz In Progress '
 'Curfew Violations ' 'Damage Property-Rpt Only '
 'Theft-Hold One Cooperative ' 'Forgery in Progress '
 'Suspected Prostitute ' 'Parking Problem ' 'Crim Sex Conduct '
 'Crank 9-1-1 Call ' 'Down Outide-One w/Fire ' 'Kidnapping/Abduction '
 'Person Threat to Jump ' 'Burglary Dwlng - Report ' 'Slumper w/Fire '
 'Down Outside-One w/Fire ' 'Lost Child ' 'Indecent Exposure '
 'Tenant Trouble ' 'Assist Fire Personnel ' 'Truancy ' 'Animal Call '
 'Forgery Report ' 'Recover Property ' 'Firecrackers ' 'PI w/trapped '
 'Road Hazard ' 'Directed Patrol ' 'Foot Beat ' 'Hotrodders '
 'Wires Down ' 'Drowning ' 'Overdose-Accidental ' 'Receive Information '
 'Unconscious ' 'Police Event ' 'Kid Trouble ' 'Animal Bite '
 'Assist a Disabled Person ' 'Test/Demo EE & CAD Oper'
 'Baby Not Breathing ' 'Assist-Public ' 'Holdup Alarm '
 'Pandemic Emergency' 'Robbery Dwlng/Person Rpt ' 'Business Check '
 'Community Engagement Meeting' 'Diabetic Problem '
 'Firefighter Needs Help ' 'Shooting Report Only '
 'Burglary Business - Report ' 'Missing Person '
 'Robbery of Biz - Report ' 'Auto Theft ' 'Audible Alarm '
 'Fire-Report Only ' 'Dead Person ' 'Elevator Emergency '
 'Aggressive Dog ' 'Overdose w/Alll ' 'Panic Alarm ' 'Check Hazard ']

In [75]:
problem_map = {
   "fight": "Violent", "assault in progress": "Violent", "assault report only": "Violent",
   "stabbing": "Violent", "shooting": "Violent", "shooting report only": "Violent",
   "robbery of person": "Violent", "robbery dwell in progress": "Violent",
   "robbery of biz in progress": "Violent", "robbery dwlng/person rpt": "Violent",
   "robbery of biz - report": "Violent", "person with a gun": "Violent",
   "person with a weapon": "Violent", "domestic with weapons": "Violent",
   "shotspotter activation": "Violent", "sound of shots fired": "Violent",
   "holdup alarm": "Violent", "kidnapping/abduction": "Violent",


   "domestic abuse-in progress": "Domestic", "domestic abuse report only": "Domestic",
   "domestic": "Domestic", "neighbor trouble": "Domestic", "tenant trouble": "Domestic",
   "retrieve prop/dom situation": "Domestic", "threats": "Domestic",
   "crim sex conduct": "Domestic", "crim sex conduct/report": "Domestic",


   "suspicious person": "Suspicious & Disorder", "suspicious vehicle": "Suspicious & Disorder",
   "disturbance": "Suspicious & Disorder", "unwanted person": "Suspicious & Disorder",
   "customer trouble": "Suspicious & Disorder", "loud party": "Suspicious & Disorder",
   "music-loud": "Suspicious & Disorder", "drunk/intoxicated person": "Suspicious & Disorder",
   "narcotics": "Suspicious & Disorder", "indecent exposure": "Suspicious & Disorder",
   "prowler": "Suspicious & Disorder", "trespass in boarded dwell": "Suspicious & Disorder",
   "unknown trouble": "Suspicious & Disorder", "curfew violations": "Suspicious & Disorder",
   "hotrodders": "Suspicious & Disorder", "suspected prostitute": "Suspicious & Disorder",
   "attempt pick-up": "Suspicious & Disorder", "walk through a building": "Suspicious & Disorder",
   "parking problem": "Suspicious & Disorder", "truancy": "Suspicious & Disorder",
   "firecrackers": "Suspicious & Disorder", "kid trouble": "Suspicious & Disorder",


   "burglary dwlng in progress": "Property & Vehicle", "burglary biz - in progress": "Property & Vehicle",
   "burglary dwlng - report": "Property & Vehicle", "burglary business - report": "Property & Vehicle",
   "theft": "Property & Vehicle", "theft-hold one cooperative": "Property & Vehicle",
   "theft - report only": "Property & Vehicle", "auto theft in progress": "Property & Vehicle",
   "auto theft": "Property & Vehicle", "bait vehicle auto theft": "Property & Vehicle",
   "recover vehicle": "Property & Vehicle", "recover property": "Property & Vehicle",
   "motor vehicle chase": "Property & Vehicle", "chase on foot": "Property & Vehicle",
   "forgery in progress": "Property & Vehicle", "forgery report": "Property & Vehicle",
   "damage property-in progress": "Property & Vehicle", "damage property-rpt only": "Property & Vehicle",
   "traffic law enforcement": "Property & Vehicle", "property damage accident": "Property & Vehicle",
   "personal injury accident": "Property & Vehicle", "property damage/hit & run": "Property & Vehicle",
   "poss personal injury acc": "Property & Vehicle", "personal inj/hit and run": "Property & Vehicle",
   "audible business alarm": "Property & Vehicle", "audible residential alarm": "Property & Vehicle",
   "audible alarm": "Property & Vehicle", "silent alarm": "Property & Vehicle",
   "panic alarm": "Property & Vehicle",


   "emotionally disturb person": "Welfare & Emergency", "check the welfare": "Welfare & Emergency",
   "attempted suicide": "Welfare & Emergency", "person threat to jump": "Welfare & Emergency",
   "down outside-one": "Welfare & Emergency", "down outside-one w/fire": "Welfare & Emergency",
   "down outide-one w/fire": "Welfare & Emergency", "slumper": "Welfare & Emergency",
   "slumper w/fire": "Welfare & Emergency", "unconscious": "Welfare & Emergency",
   "overdose-accidental": "Welfare & Emergency", "overdose w/all": "Welfare & Emergency",
   "overdose w/alll": "Welfare & Emergency", "officer needs help": "Welfare & Emergency",
   "assist an officer": "Welfare & Emergency", "assist other agency": "Welfare & Emergency",
   "assist ems personnel": "Welfare & Emergency", "assist fire personnel": "Welfare & Emergency",
   "paramedic needs help": "Welfare & Emergency", "high risk warrant entry": "Welfare & Emergency",
   "code 3": "Welfare & Emergency", "dead person": "Welfare & Emergency",
   "missing person": "Welfare & Emergency", "lost child": "Welfare & Emergency",
   "drowning": "Welfare & Emergency", "miscellaneous": "Welfare & Emergency",
   "unknown wireless/cell phone": "Welfare & Emergency", "on site": "Welfare & Emergency",
   "transportation": "Welfare & Emergency", "directed patrol": "Welfare & Emergency",
   "assist a disabled person": "Welfare & Emergency", "pandemic emergency": "Welfare & Emergency",
   "police event": "Welfare & Emergency", "receive information": "Welfare & Emergency",
   "business check": "Welfare & Emergency", "community engagement meeting": "Welfare & Emergency",
   "suspected hazard": "Welfare & Emergency", "check hazard": "Welfare & Emergency",
   "foot beat": "Welfare & Emergency", "firefighter needs help": "Welfare & Emergency",
   "assist-public": "Welfare & Emergency", "road hazard": "Welfare & Emergency",
   "wires down": "Welfare & Emergency", "animal bite": "Welfare & Emergency",
   "animal call": "Welfare & Emergency", "aggressive dog": "Welfare & Emergency",
   "fire-report only": "Welfare & Emergency", "pi w/trapped": "Welfare & Emergency",
   "elevator emergency": "Welfare & Emergency", "diabetic problem": "Welfare & Emergency",
   "baby not breathing": "Welfare & Emergency", "test/demo ee & cad oper": "Welfare & Emergency",
   "crank 9-1-1 call": "Welfare & Emergency", "aircraft crash in city": "Welfare & Emergency",
}


df['Problem_Group'] = df['Problem'].str.strip().str.lower().map(problem_map).fillna("Welfare & Emergency")
print(df['Problem_Group'].value_counts())

Problem_Group
Suspicious & Disorder    11630
Violent                   6243
Property & Vehicle        4339
Welfare & Emergency       4218
Domestic                  2866
Name: count, dtype: int64

In [76]:
# there are 208 unique primary offenses, which will also 
# need to be grouped into categories if we are using them
print(len(df['PrimaryOffense'].unique()))
print((df['PrimaryOffense'].unique()))

208
['DISCON' 'FLEE' 'NARC' 'FENTRY' 'OBSTRU' 'POVIOL' '911INT' 'CHLDAB' 'DWI'
 'BURGB' 'CIC' 'LIQLIC' 'LOITER' 'BURGD' 'AOA' 'WT' 'FORCE' 'RECVEH'
 'DWIREF' 'ASLT3' 'ASLT5' 'ASLT4' 'BURGTL' 'DASLT2' 'DASLT5' 'NOSMOK'
 'THFTSW' 'THEFT' 'HANDGN' 'NOINS' 'CSCR' 'CBYMIN' 'ASLT1' 'DASTR' 'PI'
 'ROBPAG' 'FLEEFT' 'PRIORI' 'DAMPRP' 'MISC' 'TRSPAS' 'ROBPER' 'VDNCO'
 'FOBEY' 'MJINMV' 'IPROST' 'ASLT2' 'RORDER' 'DAMMV' 'WEAP' 'DISWEA'
 'POSDPA' 'PFARM' 'PUBURN' 'SQUADA' 'FALSNM' 'CSCREG' 'RD' 'RIOT' 'HLTWEL'
 'HOUSNG' 'AUTOTH' 'TLE' 'MVTAM' 'THREAT' 'LIQMIN' 'STOLMV' 'DOMEN'
 'BEGGAR' 'CURFEW' 'DAS' 'TFPER' 'ASLTMP' 'INTPED' 'DASLT3' 'DISHSE'
 'RCPROP' 'INFO' 'OFPEN' 'PARTY' 'NODL' 'SUICDE' 'STALK' 'OPBOTT' 'CONSME'
 'LURKNG' 'CSCM' 'DAR' 'RECGUN' 'BAITV' 'VCONR' 'BOOSTR' 'SKATE' 'ASLTK9'
 'MALPUN' 'R&C' 'PD' 'PROBAT' 'PCPKUP' 'NEGLCT' 'ARSON' 'PROSTU' 'DAC'
 'HRPD' 'FIMPRS' 'DPGRAF' 'ROBBIZ' 'NSODOR' 'GUNPUB' 'TRSSCH' 'CD'
 'SHOTGN' 'CANCIP' 'TFBBIK' 'INDCON' 'HRNI' 'RPLICA' 'PINJEQ' 'XSOUND'
 'SHOPLF' 'OD' 'AGGDWI' 'MURDR' 'FINFO' 'DTHRET' 'KILDOG' 'PRKVIO' 'HRWI'
 'TFMV' 'FORG' 'CRVEHI' 'FLMOVE' 'WEAPKN' 'OBNARC' 'TRUANT' 'LIQPRK'
 'DRGOC' 'PAROLE' 'FORGCK' 'RUNWAY' 'PRXDR' 'FC' 'LITTER' 'AOFFND' 'DOA'
 'LICVIO' 'PARKCL' 'LIQMOV' 'FLEEMV' 'TAXI' 'POBSTR' 'KIDNAP' 'ESCAPE'
 'CTRFT' 'MTC' 'SHOST' 'RXFRD' 'INCEND' 'CONTMP' 'INKEEP' 'FIREWK' 'INDEX'
 'FLSTPS' 'CCATM' 'NVA' 'DANGW' 'BIKE' 'PRIVCY' 'DEPCPR' 'LANDTN' 'DISARM'
 'FALRPI' 'WEAPOT' 'CRULTY' 'DASLT1' 'ASMBLY' 'UIFIRE' 'CIGMIP' 'SEXTRF'
 'SCHEVT' 'MVTHFT' 'TAXIFR' 'MISPER' 'FATAL' 'HRUNAT' 'LIQAUD' 'FNARP'
 'PETIT' 'PAWEAP' 'EVENTS' 'RESIST' 'BIKETF' 'DWIDRE' 'PSSFIR' 'IMPPO'
 'POCKET' 'MJSMAL' 'DWICHD' 'TBLDG' 'FRPT' 'ABITE' 'CARJCK' 'CRANK' 'SWAT'
 'BADCHK' 'QTZONE' 'OFPSF' 'GRSRPT']

In [77]:
df_final = df[['ForceType', 'Sex', 'Race', 'TypeOfResistance', 'Problem_Group', 'CenterLongitude', 'CenterLatitude']]
df_final2 = df[['ForceType', 'Sex', 'Race', 'TypeOfResistance']]
df_final

,ForceType,Sex,Race,TypeOfResistance,Problem_Group,CenterLongitude,CenterLatitude
0,Bodily Force,Female,Black,tensed,Violent,-93.298111,45.015878
1,Bodily Force,Male,Black,fled,Suspicious & Disorder,-93.225106,44.898115
2,Bodily Force,Male,Black,verbal non-compliance,Suspicious & Disorder,-93.269582,44.962688
3,Less Lethal Weapons,Male,White,tensed,Welfare & Emergency,-93.204183,44.906432
4,Bodily Force,Male,White,verbal non-compliance,Violent,-93.306312,44.979777
...,...,...,...,...,...,...,...
29707,Less Lethal Weapons,Male,Native American,verbal non-compliance,Domestic,-93.272759,44.963320
29708,Bodily Force,Male,White,tensed,Welfare & Emergency,-93.277183,44.960906
29709,Less Lethal Weapons,Male,Black,other/unspecified,Domestic,-93.234562,44.966965
29711,Bodily Force,Female,other,tensed,Welfare & Emergency,-93.291053,44.996862
29712,Bodily Force,Female,Black,assaulting police officer or animal,Welfare & Emergency,-93.276738,44.971539

In [78]:
df_final.to_csv("final_data.csv")
df_final2.to_csv("final_data_2.csv")